# Configuration for attributing commits with emails to GitHub user profiles
# Used during codeowners generation.

# List the emails associated with the given username.
# The commits associated with these emails will be attributed to
# the username in this yaml map. Any number of emails may be listed.
attribution:
  brandonroberts:
    - robertsbt@gmail.com
  jpmcb:
    - john@opensauced.pizza
  nickytonline:
    - nick@nickyt.co
    - nick@opensauced.pizza
  bdougie:
    - bdougie@users.noreply.github.com
  zeucapua:
    - coding@zeu.dev
  bekahhw:
    - BekahHW@users.noreply.github.com
  isabensusan:
    - isabensusan@gmail.com
