import { Meta, StoryObj } from "@storybook/react";
import IssuesChart from "./IssuesChart";

type Story = StoryObj<typeof IssuesChart>;

const meta: Meta<typeof IssuesChart> = {
  title: "Components/Graphs/IssuesChart",
  component: IssuesChart,
  args: {
    stats: generate30DaysData(),
    range: 30,
    velocity: 171,
    syncId: 1234,
    isLoading: false,
  },
};

export default meta;

export const Days30: Story = {
  args: {
    stats: generate30DaysData(),
    range: 30,
    velocity: 171,
    syncId: 1234,
  },
};

export const Days7: Story = {
  args: {
    stats: generate7DaysData(),
    range: 7,
    velocity: 0,
    syncId: 1234,
  },
};

export const Days90: Story = {
  args: {
    stats: generate90DaysData(),
    range: 90,
    velocity: 276,
    syncId: 1234,
  },
};

export const LoadingState: Story = {
  args: {
    isLoading: true,
  },
};

function generate30DaysData() {
  return [
    {
      bucket: "2024-04-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 0,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-08T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 16,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 13,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 427,
    },
    {
      bucket: "2024-04-09T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 4,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 14,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 257,
    },
    {
      bucket: "2024-04-10T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 12,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-11T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 5,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 0,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-12T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 4,
      member_associated_issues: 0,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-13T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 2,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-14T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-15T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 15,
    },
    {
      bucket: "2024-04-16T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 101,
    },
    {
      bucket: "2024-04-17T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 512,
    },
    {
      bucket: "2024-04-18T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 2,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-19T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 11,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 338,
    },
    {
      bucket: "2024-04-20T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-21T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 2,
      closed_issues: 1,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-22T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 40,
    },
    {
      bucket: "2024-04-23T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 18,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 31,
    },
    {
      bucket: "2024-04-24T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 12,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 7,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 37,
    },
    {
      bucket: "2024-04-25T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 6,
      member_associated_issues: 0,
      non_associated_issues: 15,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 54,
    },
    {
      bucket: "2024-04-26T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 1,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 11,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 462,
    },
    {
      bucket: "2024-04-27T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 2,
      owner_associated_issues: 0,
      opened_issues: 2,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-28T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 5,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 1,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 16,
    },
    {
      bucket: "2024-04-29T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 3,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 2,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 55,
    },
    {
      bucket: "2024-04-30T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 1,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 26,
    },
    {
      bucket: "2024-05-01T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 5,
      reopened_issues: 3,
      spam_issues: 0,
      issue_velocity: 8,
    },
    {
      bucket: "2024-05-02T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 17,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 8,
      reopened_issues: 3,
      spam_issues: 0,
      issue_velocity: 45,
    },
    {
      bucket: "2024-05-03T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 6,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-05-04T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 7,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 735,
    },
    {
      bucket: "2024-05-05T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 117,
    },
    {
      bucket: "2024-05-06T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 64,
    },
    {
      bucket: "2024-05-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 31,
    },
  ];
}

function generate7DaysData() {
  return [
    {
      bucket: "2024-05-01T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 5,
      reopened_issues: 3,
      spam_issues: 0,
      issue_velocity: 8,
    },
    {
      bucket: "2024-05-02T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 17,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 8,
      reopened_issues: 3,
      spam_issues: 0,
      issue_velocity: 45,
    },
    {
      bucket: "2024-05-03T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 6,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-05-04T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 7,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 735,
    },
    {
      bucket: "2024-05-05T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 117,
    },
    {
      bucket: "2024-05-06T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 64,
    },
    {
      bucket: "2024-05-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 31,
    },
  ];
}

function generate90DaysData() {
  return [
    {
      bucket: "2024-02-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 12,
    },
    {
      bucket: "2024-02-08T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 9,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 237,
    },
    {
      bucket: "2024-02-09T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 6,
    },
    {
      bucket: "2024-02-10T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 248,
    },
    {
      bucket: "2024-02-11T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 1,
      non_associated_issues: 18,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 20,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1013,
    },
    {
      bucket: "2024-02-12T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-02-13T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 21,
      owner_associated_issues: 0,
      opened_issues: 13,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 3,
    },
    {
      bucket: "2024-02-14T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 15,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-02-15T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 1,
      non_associated_issues: 26,
      owner_associated_issues: 0,
      opened_issues: 16,
      closed_issues: 12,
      reopened_issues: 2,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-02-16T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 1,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-02-17T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 2,
      owner_associated_issues: 0,
      opened_issues: 2,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-02-18T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 4,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-02-19T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 7,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 752,
    },
    {
      bucket: "2024-02-20T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 23,
      owner_associated_issues: 0,
      opened_issues: 13,
      closed_issues: 11,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 11,
    },
    {
      bucket: "2024-02-21T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 7,
      member_associated_issues: 2,
      non_associated_issues: 32,
      owner_associated_issues: 0,
      opened_issues: 10,
      closed_issues: 30,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 192,
    },
    {
      bucket: "2024-02-22T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 1,
      non_associated_issues: 15,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 47,
    },
    {
      bucket: "2024-02-23T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 20,
    },
    {
      bucket: "2024-02-24T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 1,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-02-25T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 1,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-02-26T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 1,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 4,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 366,
    },
    {
      bucket: "2024-02-27T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 1,
      non_associated_issues: 15,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 7,
    },
    {
      bucket: "2024-02-28T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 9,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 18,
    },
    {
      bucket: "2024-02-29T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 5,
    },
    {
      bucket: "2024-03-01T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 5,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-03-02T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 22,
    },
    {
      bucket: "2024-03-03T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 3,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-03-04T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 18,
      owner_associated_issues: 0,
      opened_issues: 11,
      closed_issues: 7,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 62,
    },
    {
      bucket: "2024-03-05T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-03-06T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 2,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 334,
    },
    {
      bucket: "2024-03-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 7,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 46,
    },
    {
      bucket: "2024-03-08T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 2,
      non_associated_issues: 17,
      owner_associated_issues: 0,
      opened_issues: 15,
      closed_issues: 9,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 112,
    },
    {
      bucket: "2024-03-09T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-03-10T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 2,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 12,
    },
    {
      bucket: "2024-03-11T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 8,
      member_associated_issues: 3,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 9,
    },
    {
      bucket: "2024-03-12T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 9,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 523,
    },
    {
      bucket: "2024-03-13T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 1,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 523,
    },
    {
      bucket: "2024-03-14T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 3,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 10,
      closed_issues: 6,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 775,
    },
    {
      bucket: "2024-03-15T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 19,
      owner_associated_issues: 0,
      opened_issues: 13,
      closed_issues: 7,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 18,
    },
    {
      bucket: "2024-03-16T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 1,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-03-17T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 577,
    },
    {
      bucket: "2024-03-18T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 6,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 16,
    },
    {
      bucket: "2024-03-19T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 1,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 1,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 85,
    },
    {
      bucket: "2024-03-20T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1,
    },
    {
      bucket: "2024-03-21T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-03-22T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 1,
      non_associated_issues: 22,
      owner_associated_issues: 0,
      opened_issues: 11,
      closed_issues: 12,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 305,
    },
    {
      bucket: "2024-03-23T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 18,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 18,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 878,
    },
    {
      bucket: "2024-03-24T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1822,
    },
    {
      bucket: "2024-03-25T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 12,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 4,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 101,
    },
    {
      bucket: "2024-03-26T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 9,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 434,
    },
    {
      bucket: "2024-03-27T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 4,
      member_associated_issues: 0,
      non_associated_issues: 20,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 19,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 42,
    },
    {
      bucket: "2024-03-28T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 23,
      owner_associated_issues: 0,
      opened_issues: 10,
      closed_issues: 18,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 47,
    },
    {
      bucket: "2024-03-29T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 18,
      member_associated_issues: 2,
      non_associated_issues: 26,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 39,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 509,
    },
    {
      bucket: "2024-03-30T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 12,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 14,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1346,
    },
    {
      bucket: "2024-03-31T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 1196,
    },
    {
      bucket: "2024-04-01T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 16,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 9,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 179,
    },
    {
      bucket: "2024-04-02T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 7,
      member_associated_issues: 0,
      non_associated_issues: 4,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 3,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 847,
    },
    {
      bucket: "2024-04-03T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 10,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 581,
    },
    {
      bucket: "2024-04-04T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 7,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 24,
    },
    {
      bucket: "2024-04-05T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 2,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 702,
    },
    {
      bucket: "2024-04-06T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 2,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 2,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 2,
      closed_issues: 19,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 266,
    },
    {
      bucket: "2024-04-08T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 16,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 13,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 427,
    },
    {
      bucket: "2024-04-09T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 4,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 14,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 257,
    },
    {
      bucket: "2024-04-10T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 12,
      owner_associated_issues: 0,
      opened_issues: 9,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-11T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 5,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 0,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-12T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 4,
      member_associated_issues: 0,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-13T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 2,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-14T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 0,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-15T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 15,
    },
    {
      bucket: "2024-04-16T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 101,
    },
    {
      bucket: "2024-04-17T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 7,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 512,
    },
    {
      bucket: "2024-04-18T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 2,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-19T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 5,
      member_associated_issues: 0,
      non_associated_issues: 14,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 11,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 338,
    },
    {
      bucket: "2024-04-20T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-21T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 2,
      closed_issues: 1,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-22T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 8,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 40,
    },
    {
      bucket: "2024-04-23T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 0,
      non_associated_issues: 18,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 31,
    },
    {
      bucket: "2024-04-24T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 12,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 7,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 37,
    },
    {
      bucket: "2024-04-25T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 6,
      member_associated_issues: 0,
      non_associated_issues: 15,
      owner_associated_issues: 0,
      opened_issues: 8,
      closed_issues: 13,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 54,
    },
    {
      bucket: "2024-04-26T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 3,
      member_associated_issues: 1,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 11,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 462,
    },
    {
      bucket: "2024-04-27T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 2,
      owner_associated_issues: 0,
      opened_issues: 2,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-04-28T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 5,
      owner_associated_issues: 0,
      opened_issues: 4,
      closed_issues: 1,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 16,
    },
    {
      bucket: "2024-04-29T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 3,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 6,
      closed_issues: 2,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 55,
    },
    {
      bucket: "2024-04-30T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 1,
      non_associated_issues: 6,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 4,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 26,
    },
    {
      bucket: "2024-05-01T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 11,
      owner_associated_issues: 0,
      opened_issues: 3,
      closed_issues: 5,
      reopened_issues: 3,
      spam_issues: 0,
      issue_velocity: 8,
    },
    {
      bucket: "2024-05-02T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 17,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 8,
      reopened_issues: 3,
      spam_issues: 0,
      issue_velocity: 45,
    },
    {
      bucket: "2024-05-03T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 10,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 6,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 0,
    },
    {
      bucket: "2024-05-04T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 13,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 7,
      reopened_issues: 1,
      spam_issues: 0,
      issue_velocity: 735,
    },
    {
      bucket: "2024-05-05T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 1,
      member_associated_issues: 0,
      non_associated_issues: 3,
      owner_associated_issues: 0,
      opened_issues: 1,
      closed_issues: 3,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 117,
    },
    {
      bucket: "2024-05-06T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 2,
      member_associated_issues: 0,
      non_associated_issues: 8,
      owner_associated_issues: 0,
      opened_issues: 5,
      closed_issues: 5,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 64,
    },
    {
      bucket: "2024-05-07T00:00:00.000Z",
      collaborator_associated_issues: 0,
      contributor_associated_issues: 0,
      member_associated_issues: 0,
      non_associated_issues: 9,
      owner_associated_issues: 0,
      opened_issues: 7,
      closed_issues: 2,
      reopened_issues: 0,
      spam_issues: 0,
      issue_velocity: 31,
    },
  ];
}
