import { Meta, StoryObj } from "@storybook/react";
import PRChart from "./PRChart";

type Story = StoryObj<typeof PRChart>;

const meta: Meta<typeof PRChart> = {
  title: "Components/Graphs/PRChart",
  component: PRChart,
  args: {
    stats: generate30DaysData(),
    range: 30,
    velocity: 0,
    syncId: 1234,
    isLoading: false,
  },
};

export default meta;

export const Days30: Story = {
  args: {
    stats: generate30DaysData(),
    range: 30,
    velocity: 0,
    syncId: 1234,
  },
};

export const Days7: Story = {
  args: {
    stats: generate7DaysData(),
    range: 7,
    velocity: 0,
    syncId: 1234,
  },
};

export const Days90: Story = {
  args: {
    stats: generate90DaysData(),
    range: 90,
    velocity: 0,
    syncId: 1234,
  },
};

export const LoadingState: Story = {
  args: {
    isLoading: true,
  },
};

function generate30DaysData() {
  return [
    {
      bucket: "2024-04-08T00:00:00.000Z",
      prs_count: 27,
      collaborator_associated_prs: 5,
      contributor_associated_prs: 8,
      member_associated_prs: 12,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 16,
      draft_prs: 2,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-09T00:00:00.000Z",
      prs_count: 25,
      collaborator_associated_prs: 6,
      contributor_associated_prs: 6,
      member_associated_prs: 10,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 9,
      draft_prs: 5,
      active_prs: 16,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-10T00:00:00.000Z",
      prs_count: 21,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 12,
      member_associated_prs: 4,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 3,
      active_prs: 17,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-11T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 0,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-12T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 13,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 4,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-13T00:00:00.000Z",
      prs_count: 2,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 0,
      member_associated_prs: 1,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 0,
      active_prs: 1,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-14T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 4,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-15T00:00:00.000Z",
      prs_count: 13,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 4,
      member_associated_prs: 8,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 5,
      active_prs: 10,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-16T00:00:00.000Z",
      prs_count: 20,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 11,
      member_associated_prs: 6,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 5,
      draft_prs: 4,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-17T00:00:00.000Z",
      prs_count: 12,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 5,
      member_associated_prs: 6,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 1,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-18T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 11,
      member_associated_prs: 4,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 5,
      active_prs: 19,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-19T00:00:00.000Z",
      prs_count: 22,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 13,
      member_associated_prs: 5,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 5,
      draft_prs: 7,
      active_prs: 17,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-20T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 1,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 1,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-21T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-22T00:00:00.000Z",
      prs_count: 10,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 4,
      member_associated_prs: 4,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 1,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-23T00:00:00.000Z",
      prs_count: 22,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 12,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 9,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-24T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 14,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 4,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-25T00:00:00.000Z",
      prs_count: 25,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 12,
      member_associated_prs: 10,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 3,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-26T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 4,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-27T00:00:00.000Z",
      prs_count: 1,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 0,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 1,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-29T00:00:00.000Z",
      prs_count: 11,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 7,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 5,
      draft_prs: 3,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-30T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 10,
      member_associated_prs: 2,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 2,
      active_prs: 13,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-01T00:00:00.000Z",
      prs_count: 21,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 16,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 1,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-02T00:00:00.000Z",
      prs_count: 12,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 5,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 3,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-03T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 11,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 8,
      active_prs: 16,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-06T00:00:00.000Z",
      prs_count: 16,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 12,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 14,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-07T00:00:00.000Z",
      prs_count: 10,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 3,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 3,
      active_prs: 9,
      spam_prs: 0,
      pr_velocity: 0,
    },
  ];
}

function generate7DaysData() {
  return [
    {
      bucket: "2024-04-30T00:00:00.000Z",
      prs_count: 15,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 11,
      member_associated_prs: 0,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 9,
      draft_prs: 1,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-01T00:00:00.000Z",
      prs_count: 27,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 20,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 1,
      closed_prs: 6,
      draft_prs: 1,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-02T00:00:00.000Z",
      prs_count: 14,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 7,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 3,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-03T00:00:00.000Z",
      prs_count: 21,
      collaborator_associated_prs: 4,
      contributor_associated_prs: 11,
      member_associated_prs: 4,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 5,
      draft_prs: 8,
      active_prs: 16,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-04T00:00:00.000Z",
      prs_count: 2,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 1,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 0,
      active_prs: 0,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-06T00:00:00.000Z",
      prs_count: 20,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 16,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 6,
      draft_prs: 3,
      active_prs: 14,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-07T00:00:00.000Z",
      prs_count: 11,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 4,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 9,
      spam_prs: 0,
      pr_velocity: 0,
    },
  ];
}

function generate90DaysData() {
  return [
    {
      bucket: "2024-02-07T00:00:00.000Z",
      prs_count: 8,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 0,
      active_prs: 5,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-08T00:00:00.000Z",
      prs_count: 22,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 10,
      member_associated_prs: 11,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 4,
      active_prs: 19,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-09T00:00:00.000Z",
      prs_count: 10,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 2,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 1,
      active_prs: 8,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-10T00:00:00.000Z",
      prs_count: 6,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 4,
      member_associated_prs: 2,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 1,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-11T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 2,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-12T00:00:00.000Z",
      prs_count: 13,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 4,
      member_associated_prs: 8,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 6,
      active_prs: 12,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-13T00:00:00.000Z",
      prs_count: 8,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 2,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 3,
      active_prs: 8,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-14T00:00:00.000Z",
      prs_count: 15,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 6,
      member_associated_prs: 8,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 2,
      active_prs: 14,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-15T00:00:00.000Z",
      prs_count: 11,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 6,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 1,
      active_prs: 9,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-16T00:00:00.000Z",
      prs_count: 5,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 2,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 2,
      active_prs: 5,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-17T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 2,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-18T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 0,
      member_associated_prs: 2,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 2,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-19T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 0,
      member_associated_prs: 5,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 4,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-20T00:00:00.000Z",
      prs_count: 13,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 4,
      member_associated_prs: 8,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 3,
      active_prs: 12,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-21T00:00:00.000Z",
      prs_count: 13,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 8,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 3,
      active_prs: 9,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-22T00:00:00.000Z",
      prs_count: 28,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 11,
      member_associated_prs: 10,
      non_associated_prs: 7,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 6,
      draft_prs: 4,
      active_prs: 22,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-23T00:00:00.000Z",
      prs_count: 8,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 4,
      member_associated_prs: 4,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 1,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-24T00:00:00.000Z",
      prs_count: 2,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 1,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-25T00:00:00.000Z",
      prs_count: 2,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 0,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-26T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 6,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 3,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-27T00:00:00.000Z",
      prs_count: 15,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 5,
      member_associated_prs: 5,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 13,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-28T00:00:00.000Z",
      prs_count: 18,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 6,
      member_associated_prs: 11,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 7,
      active_prs: 14,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-02-29T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 4,
      member_associated_prs: 14,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 13,
      draft_prs: 2,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-01T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 2,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-02T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 1,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-04T00:00:00.000Z",
      prs_count: 6,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 3,
      member_associated_prs: 1,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 1,
      active_prs: 4,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-05T00:00:00.000Z",
      prs_count: 10,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 5,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 4,
      active_prs: 9,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-06T00:00:00.000Z",
      prs_count: 20,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 9,
      member_associated_prs: 8,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 4,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-07T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 10,
      member_associated_prs: 6,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 4,
      draft_prs: 6,
      active_prs: 13,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-08T00:00:00.000Z",
      prs_count: 13,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 8,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 5,
      active_prs: 13,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-09T00:00:00.000Z",
      prs_count: 6,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-10T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 2,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 3,
      active_prs: 4,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-11T00:00:00.000Z",
      prs_count: 12,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 3,
      member_associated_prs: 5,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 2,
      active_prs: 12,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-12T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 4,
      member_associated_prs: 2,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 2,
      active_prs: 5,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-13T00:00:00.000Z",
      prs_count: 11,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 8,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 4,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-14T00:00:00.000Z",
      prs_count: 9,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 5,
      member_associated_prs: 2,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 2,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-15T00:00:00.000Z",
      prs_count: 33,
      collaborator_associated_prs: 13,
      contributor_associated_prs: 7,
      member_associated_prs: 13,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 7,
      draft_prs: 11,
      active_prs: 26,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-16T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 1,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-17T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 1,
      member_associated_prs: 1,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-18T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 1,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 3,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-19T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 5,
      contributor_associated_prs: 5,
      member_associated_prs: 5,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 5,
      active_prs: 17,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-20T00:00:00.000Z",
      prs_count: 12,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 10,
      member_associated_prs: 2,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 4,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-21T00:00:00.000Z",
      prs_count: 6,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 2,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 4,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-22T00:00:00.000Z",
      prs_count: 6,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 0,
      member_associated_prs: 2,
      non_associated_prs: 4,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 2,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-23T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 1,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 0,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-24T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 2,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 2,
      active_prs: 4,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-25T00:00:00.000Z",
      prs_count: 6,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 2,
      member_associated_prs: 1,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 0,
      active_prs: 5,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-26T00:00:00.000Z",
      prs_count: 16,
      collaborator_associated_prs: 6,
      contributor_associated_prs: 5,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 5,
      active_prs: 16,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-27T00:00:00.000Z",
      prs_count: 16,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 7,
      member_associated_prs: 5,
      non_associated_prs: 4,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 5,
      active_prs: 14,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-28T00:00:00.000Z",
      prs_count: 22,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 16,
      member_associated_prs: 5,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 5,
      active_prs: 19,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-29T00:00:00.000Z",
      prs_count: 20,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 12,
      member_associated_prs: 6,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 5,
      active_prs: 18,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-30T00:00:00.000Z",
      prs_count: 2,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 1,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-03-31T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 0,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 4,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-01T00:00:00.000Z",
      prs_count: 15,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 9,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 4,
      active_prs: 13,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-02T00:00:00.000Z",
      prs_count: 18,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 10,
      member_associated_prs: 2,
      non_associated_prs: 4,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 2,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-03T00:00:00.000Z",
      prs_count: 8,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 2,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 2,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-04T00:00:00.000Z",
      prs_count: 9,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 3,
      member_associated_prs: 3,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 3,
      active_prs: 8,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-05T00:00:00.000Z",
      prs_count: 10,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 6,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 8,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-06T00:00:00.000Z",
      prs_count: 1,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 0,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 1,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-07T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 0,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 0,
      active_prs: 1,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-08T00:00:00.000Z",
      prs_count: 12,
      collaborator_associated_prs: 4,
      contributor_associated_prs: 1,
      member_associated_prs: 5,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 2,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-09T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 5,
      contributor_associated_prs: 3,
      member_associated_prs: 6,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 5,
      active_prs: 16,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-10T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 11,
      member_associated_prs: 3,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 17,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-11T00:00:00.000Z",
      prs_count: 2,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 0,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 2,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-12T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 12,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 4,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-13T00:00:00.000Z",
      prs_count: 1,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 0,
      member_associated_prs: 0,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 1,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-14T00:00:00.000Z",
      prs_count: 4,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 4,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-15T00:00:00.000Z",
      prs_count: 11,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 3,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 5,
      active_prs: 10,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-16T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 11,
      member_associated_prs: 3,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 4,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-17T00:00:00.000Z",
      prs_count: 11,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 4,
      member_associated_prs: 6,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-18T00:00:00.000Z",
      prs_count: 19,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 11,
      member_associated_prs: 4,
      non_associated_prs: 3,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 5,
      active_prs: 19,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-19T00:00:00.000Z",
      prs_count: 18,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 11,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 7,
      active_prs: 17,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-20T00:00:00.000Z",
      prs_count: 3,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 2,
      member_associated_prs: 1,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 3,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-21T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-22T00:00:00.000Z",
      prs_count: 8,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 4,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 1,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-23T00:00:00.000Z",
      prs_count: 20,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 12,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 9,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-24T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 12,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 4,
      active_prs: 15,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-25T00:00:00.000Z",
      prs_count: 20,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 11,
      member_associated_prs: 6,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 3,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-26T00:00:00.000Z",
      prs_count: 7,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 3,
      member_associated_prs: 4,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 7,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-27T00:00:00.000Z",
      prs_count: 1,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 1,
      member_associated_prs: 0,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 0,
      draft_prs: 0,
      active_prs: 1,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-29T00:00:00.000Z",
      prs_count: 8,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 4,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 6,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-04-30T00:00:00.000Z",
      prs_count: 16,
      collaborator_associated_prs: 3,
      contributor_associated_prs: 9,
      member_associated_prs: 2,
      non_associated_prs: 2,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 3,
      draft_prs: 2,
      active_prs: 13,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-01T00:00:00.000Z",
      prs_count: 21,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 16,
      member_associated_prs: 3,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 1,
      closed_prs: 0,
      draft_prs: 1,
      active_prs: 20,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-02T00:00:00.000Z",
      prs_count: 12,
      collaborator_associated_prs: 0,
      contributor_associated_prs: 5,
      member_associated_prs: 7,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 3,
      active_prs: 11,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-03T00:00:00.000Z",
      prs_count: 17,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 10,
      member_associated_prs: 4,
      non_associated_prs: 1,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 8,
      active_prs: 16,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-06T00:00:00.000Z",
      prs_count: 16,
      collaborator_associated_prs: 1,
      contributor_associated_prs: 12,
      member_associated_prs: 3,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 2,
      draft_prs: 3,
      active_prs: 14,
      spam_prs: 0,
      pr_velocity: 0,
    },
    {
      bucket: "2024-05-07T00:00:00.000Z",
      prs_count: 10,
      collaborator_associated_prs: 2,
      contributor_associated_prs: 3,
      member_associated_prs: 5,
      non_associated_prs: 0,
      owner_associated_prs: 0,
      accepted_prs: 0,
      closed_prs: 1,
      draft_prs: 3,
      active_prs: 9,
      spam_prs: 0,
      pr_velocity: 0,
    },
  ];
}
