export const STUB_DEV_CARDS = [
  {
    username: "foxyblocks",
    name: "Chris Schlensker",
    avatarURL: "https://avatars.githubusercontent.com/u/555044?v=4",
    prs: 2,
    contributions: 57,
    bio: "This is the story all about how my life got flipped turned upside down, and I'd like to take a minute just sit right there, I'll tell you how I became the prince of a town called Bel-Air.",
    prVelocity: 102,
  },
  {
    username: "codebytere",
    name: "Shelley Vohr",
    avatarURL: "https://avatars.githubusercontent.com/u/2036040?v=4",
    prs: 31,
    contributions: 1,
    bio: "This is the story all about how my life got flipped turned upside down, and I'd like to take a minute just sit right there, I'll tell you how I became the prince of a town called Bel-Air.",
    prVelocity: 67,
  },
  {
    username: "miniak",
    name: "Milan Burda",
    avatarURL: "https://avatars.githubusercontent.com/u/1281234?v=4",
    prs: 31,
    contributions: 1,
    bio: "This is the story all about how my life got flipped turned upside down, and I'd like to take a minute just sit right there, I'll tell you how I became the prince of a town called Bel-Air.",
    prVelocity: 67,
  },
  {
    username: "ckerr",
    name: "Charles Kerr",
    avatarURL: "https://avatars.githubusercontent.com/u/70381?v=4",
    prs: 31,
    contributions: 1,
    bio: "This is the story all about how my life got flipped turned upside down, and I'd like to take a minute just sit right there, I'll tell you how I became the prince of a town called Bel-Air.",
    prVelocity: 67,
  },
  {
    username: "JeanMeche",
    name: "Matthieu Riegler",
    avatarURL: "https://avatars.githubusercontent.com/u/1300985?v=4",
    prs: 31,
    contributions: 1,
    bio: "This is the story all about how my life got flipped turned upside down, and I'd like to take a minute just sit right there, I'll tell you how I became the prince of a town called Bel-Air.",
    prVelocity: 67,
  },
  {
    username: "annacmc",
    name: "Anna McPhee",
    avatarURL: "https://avatars.githubusercontent.com/u/30754158?v=4",
    prs: 31,
    contributions: 1,
    bio: "This is the story all about how my life got flipped turned upside down, and I'd like to take a minute just sit right there, I'll tell you how I became the prince of a town called Bel-Air.",
    prVelocity: 67,
  },
] as const;
