on:
  schedule:
  - cron: 00 08 * * 6
name: Weekly Top5 Issue Closure
jobs:
  cycle-weekly-close:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
    - name: weekly-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: top5
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
