name: "Assign issues with .take"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  take-issue:
    name: Disable take issue
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: take an issue
        uses: bdougie/take-action@main
        with:
          issueCurrentlyAssignedMessage: Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor.
          token: ${{ secrets.GITHUB_TOKEN }}
