name: "Assign issues with .take"
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  take-issue:
    name: Disable take issue
    timeout-minutes: 10
    steps:
      - name: take an issue
        uses: bdougie/take-action@v1.6.1
        with:
          issueCurrentlyAssignedMessage: Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor.
          token: ${{ secrets.GITHUB_TOKEN }}
          blockingLabels: 👀 needs triage,blocked,core team work,needs design,duplicate
          blockingLabelsMessage: The issue you are trying to assign yourself is blocked until it can be triaged or by another label on the issue.
